### ISSUE TITLE
Context menu (right button click) on checkbox at left of row causes exception

### ISSUE THREAD

**Issue by rsivan** [tsuoanttila/GridExtensionPack#6]
Clicking in that area should just be ignored.
Trace:
`Caused by: java.lang.NullPointerException
	at org.vaadin.teemusa.gridextensions.contextclick.ContextClickEvent.<init>(ContextClickEvent.java:18)
	at org.vaadin.teemusa.gridextensions.contextclick.ContextClickExtension$1.contextClick(ContextClickExtension.java:28)
	... 33 more`

**Comment by tsuoanttila** [comment]
Sorry for slow response. There is a missing null check for property check as the selection column actually does not have a propery attached to it. Will fix this ASAP
